### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by llq520** [HelllGuest/Qualcomm_tools#1]
hi sir.i have tried some py script on windows cannot works.and my version is 3.7.0.how need i do it? or on other way must be execute on linux or unix?

E:\>python ptool.py
  File "ptool.py", line 38
    print "\nERROR: Can't create the file log_singleimage.txt"
                                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nERROR
: Can't create the file log_singleimage.txt")?

**Comment by HelllGuest** [comment]
Use python 2
